import {Router} from "express"; import bcrypt from "bcryptjs"; import jwt from "jsonwebtoken"; import crypto from "node:crypto"; import {db} from "../db/database.js"; import {requireAuth} from "../middleware/auth.js"; import { sendNotification } from "../services/notifications.js"; import {securityConfig,loginBlocked,registerLoginFailure,clearLoginFailures} from "../services/security.js";
const r=Router(),secret=process.env.JWT_SECRET||"dev-only-change-me";

r.post("/solicitar-recuperacion",async(req,res)=>{
 const correo=String(req.body?.correo||"").trim().toLowerCase();
 if(!correo)return res.status(400).json({error:"Correo obligatorio"});
 const u=db.prepare("SELECT u.id,u.empresa_id,u.nombre,u.correo,e.nombre empresa FROM usuarios u JOIN empresas e ON e.id=u.empresa_id WHERE lower(u.correo)=lower(?) AND u.estado=1 AND e.estado=1 LIMIT 1").get(correo);
 if(u){ const raw=crypto.randomBytes(32).toString("hex"),hash=crypto.createHash("sha256").update(raw).digest("hex"); db.prepare("UPDATE recuperacion_claves SET usado=1 WHERE usuario_id=? AND usado=0").run(u.id); db.prepare("INSERT INTO recuperacion_claves(usuario_id,empresa_id,token_hash,expira_en) VALUES(?,?,?,datetime('now','+30 minutes'))").run(u.id,u.empresa_id,hash); const base=process.env.FRONTEND_ORIGIN||"http://localhost:5173"; const enlace=`${base}/?reset=${raw}`; sendNotification({empresaId:u.empresa_id,event:"RECUPERACION_CLAVE",to:u.correo,vars:{nombre:u.nombre,empresa:u.empresa,enlace}}).then(result=>{
   if(!result?.ok) console.error("[NOTIFICACIONES] Recuperación no enviada:",result?.message||result?.error||"Error desconocido");
 }).catch(e=>console.error("[NOTIFICACIONES] Recuperación:",e.message)); }
 res.json({ok:true,message:"Si el correo existe, recibirá instrucciones para recuperar el acceso."});
});

r.post("/restablecer-clave",async(req,res)=>{
 const token=String(req.body?.token||"").trim(),password=String(req.body?.password||""); if(!token||!password)return res.status(400).json({error:"Token y nueva contraseña son obligatorios"});
 const hash=crypto.createHash("sha256").update(token).digest("hex"),r0=db.prepare("SELECT rc.*,u.nombre,u.correo,e.nombre empresa FROM recuperacion_claves rc JOIN usuarios u ON u.id=rc.usuario_id JOIN empresas e ON e.id=rc.empresa_id WHERE rc.token_hash=? AND rc.usado=0 AND datetime(rc.expira_en)>datetime('now') LIMIT 1").get(hash);
 if(!r0)return res.status(400).json({error:"El enlace de recuperación es inválido o ha expirado"});
 const cfg=securityConfig(r0.empresa_id),policyError=(()=>{const min=Number(cfg.password_min_length||8);if(password.length<min)return `La contraseña debe tener al menos ${min} caracteres`;if(cfg.password_upper&&!/[A-Z]/.test(password))return "La contraseña debe contener una mayúscula";if(cfg.password_lower&&!/[a-z]/.test(password))return "La contraseña debe contener una minúscula";if(cfg.password_number&&!/\d/.test(password))return "La contraseña debe contener un número";if(cfg.password_special&&!/[^A-Za-z0-9]/.test(password))return "La contraseña debe contener un carácter especial";return ""})(); if(policyError)return res.status(400).json({error:policyError});
 db.prepare("UPDATE usuarios SET password_hash=? WHERE id=?").run(bcrypt.hashSync(password,12),r0.usuario_id); db.prepare("UPDATE recuperacion_claves SET usado=1 WHERE id=?").run(r0.id); db.prepare("UPDATE sesiones SET fecha_cierre=CURRENT_TIMESTAMP WHERE usuario_id=? AND fecha_cierre IS NULL").run(r0.usuario_id); sendNotification({empresaId:r0.empresa_id,event:"CAMBIO_CLAVE",to:r0.correo,vars:{nombre:r0.nombre,empresa:r0.empresa}}).catch(e=>console.warn("[NOTIFICACIONES] Cambio clave:",e.message)); res.json({ok:true});
});

r.post("/login",(req,res)=>{const correo=String(req.body?.correo||"").trim().toLowerCase(),password=req.body?.password||"",ip=req.ip||"";if(!correo||!password)return res.status(400).json({error:"Correo y contraseña son obligatorios"});const userByEmail=db.prepare("SELECT empresa_id FROM usuarios WHERE lower(correo)=lower(?) ORDER BY id LIMIT 1").get(correo);const cfg=userByEmail?securityConfig(userByEmail.empresa_id):{session_minutes:480,max_login_attempts:5,lock_minutes:15};if(loginBlocked(correo,ip))return res.status(429).json({error:`Acceso temporalmente bloqueado. Intente nuevamente en ${cfg.lock_minutes||15} minutos.`});const u=db.prepare("SELECT u.*,r.nombre rol,e.nombre empresa FROM usuarios u JOIN roles r ON r.id=u.rol_id JOIN empresas e ON e.id=u.empresa_id WHERE lower(u.correo)=lower(?) AND u.estado=1 AND e.estado=1").get(correo);if(!u||!bcrypt.compareSync(password,u.password_hash)){const f=registerLoginFailure(correo,ip,cfg);return res.status(f.blocked?429:401).json({error:f.blocked?`Demasiados intentos. Acceso bloqueado durante ${cfg.lock_minutes||15} minutos.`:"Credenciales incorrectas"});}clearLoginFailures(correo,ip);const age=Math.min(24*60*60,Math.max(15,Number(cfg.session_minutes||480)/60))*60*1000,jti=crypto.randomUUID(),token=jwt.sign({sub:u.id,jti,empresa_id:u.empresa_id},secret,{expiresIn:Math.round(age/1000)});db.prepare("UPDATE usuarios SET ultimo_login=CURRENT_TIMESTAMP WHERE id=?").run(u.id);db.prepare("INSERT INTO sesiones(usuario_id,token_jti,fecha_expira,ip,user_agent) VALUES(?,?,?,?,?)").run(u.id,jti,new Date(Date.now()+age).toISOString(),ip,req.get("user-agent")||"");db.prepare("INSERT INTO auditoria(empresa_id,usuario_id,accion,modulo,detalle,ip,resultado,metodo,ruta,user_agent) VALUES(?,?,?,?,?,?,?,?,?,?)").run(u.empresa_id,u.id,"LOGIN","AUTENTICACION","Inicio de sesión",ip,"OK",req.method,req.originalUrl,req.get("user-agent")||"");res.cookie("itgps_token",token,{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",maxAge:age});res.json({ok:true})});
r.post("/logout",requireAuth,(req,res)=>{try{const p=jwt.verify(req.cookies.itgps_token,secret);db.prepare("UPDATE sesiones SET fecha_cierre=CURRENT_TIMESTAMP WHERE token_jti=?").run(p.jti)}catch{};db.prepare("INSERT INTO auditoria(empresa_id,usuario_id,accion,modulo,detalle,ip,resultado,metodo,ruta,user_agent) VALUES(?,?,?,?,?,?,?,?,?,?)").run(req.user.empresa_id,req.user.id,"LOGOUT","AUTENTICACION","Cierre de sesión",req.ip,"OK",req.method,req.originalUrl,req.get("user-agent")||"");res.clearCookie("itgps_token");res.json({ok:true})});
r.get("/me",requireAuth,(req,res)=>res.json({usuario:{...req.user,password_hash:undefined}})); export default r;
