import {Router} from 'express';
import {db} from '../db/database.js';
import {requireAuth,requirePermission} from '../middleware/auth.js';
import { getBrand } from '../services_documentRenderer.js';
import { buildPdf } from '../services_pdf.js';
const r=Router(); const admin=u=>u.rol==='Administrador';
function allowed(req,x){return x&&(admin(req.user)||x.empresa_id===req.user.empresa_id)}
function audit(req,a,d,e=req.user.empresa_id){try{db.prepare('INSERT INTO auditoria(empresa_id,usuario_id,accion,modulo,detalle,ip,resultado,metodo,ruta,user_agent) VALUES(?,?,?,?,?,?,?,?,?,?)').run(e,req.user.id,a,'CONTRATOS',d,req.ip,'OK',req.method,req.originalUrl,req.get('user-agent')||'')}catch{}}
function nextCode(e){const rows=db.prepare('SELECT codigo FROM contratos WHERE empresa_id=?').all(e);let m=0;for(const x of rows){const z=String(x.codigo||'').match(/^CTR-?(\d+)$/i);if(z)m=Math.max(m,Number(z[1]))}return `CTR${String(m+1).padStart(4,'0')}`}
function row(id){return db.prepare(`SELECT c.*,e.nombre empresa,cl.nombre cliente,cl.razon_social,cl.nombre_comercial,q.codigo cotizacion_codigo,s.codigo suscripcion_codigo,p.nombre plan,sv.nombre servicio FROM contratos c JOIN empresas e ON e.id=c.empresa_id JOIN clientes cl ON cl.id=c.cliente_id LEFT JOIN cotizaciones q ON q.id=c.cotizacion_id LEFT JOIN suscripciones s ON s.id=c.suscripcion_id LEFT JOIN planes p ON p.id=s.plan_id LEFT JOIN servicios sv ON sv.id=p.servicio_id WHERE c.id=?`).get(id)}
r.get('/catalogos',requireAuth,requirePermission('contratos.ver'),(req,res)=>{const e=admin(req.user)&&Number(req.query.empresa_id)?Number(req.query.empresa_id):req.user.empresa_id;const clientes=db.prepare("SELECT id,nombre,razon_social,nombre_comercial FROM clientes WHERE empresa_id=? AND estado=1 ORDER BY COALESCE(NULLIF(razon_social,''),nombre)").all(e);const cotizaciones=db.prepare("SELECT id,codigo,cliente_id,fecha,total FROM cotizaciones WHERE empresa_id=? AND estado='Aceptada' ORDER BY id DESC").all(e);const suscripciones=db.prepare("SELECT s.id,s.codigo,s.cliente_id,s.fecha_inicio,s.fecha_fin,s.precio,s.cantidad,p.nombre plan,sv.nombre servicio FROM suscripciones s JOIN planes p ON p.id=s.plan_id JOIN servicios sv ON sv.id=p.servicio_id WHERE s.empresa_id=? AND s.estado='Activa' ORDER BY s.id DESC").all(e);res.json({siguiente_codigo:nextCode(e),clientes,cotizaciones,suscripciones})});
r.get('/',requireAuth,requirePermission('contratos.ver'),(req,res)=>{const e=admin(req.user)&&Number(req.query.empresa_id)?Number(req.query.empresa_id):req.user.empresa_id,q=String(req.query.q||'').trim(),estado=String(req.query.estado||'');const p=[e];let sql=`SELECT c.*,cl.nombre cliente,cl.razon_social,cl.nombre_comercial,q.codigo cotizacion_codigo,s.codigo suscripcion_codigo FROM contratos c JOIN clientes cl ON cl.id=c.cliente_id LEFT JOIN cotizaciones q ON q.id=c.cotizacion_id LEFT JOIN suscripciones s ON s.id=c.suscripcion_id WHERE c.empresa_id=?`;if(q){sql+=' AND (c.codigo LIKE ? OR c.titulo LIKE ? OR cl.nombre LIKE ? OR cl.razon_social LIKE ? OR cl.nombre_comercial LIKE ?)';const x='%'+q+'%';p.push(x,x,x,x,x)}if(estado){sql+=' AND c.estado=?';p.push(estado)}sql+=' ORDER BY c.fecha_inicio DESC,c.id DESC LIMIT 1000';res.json({contratos:db.prepare(sql).all(...p)})});
r.get('/:id/pdf',requireAuth,requirePermission('contratos.ver'),(req,res)=>{
 const id=Number(req.params.id),h=row(id); if(!allowed(req,h))return res.status(404).json({error:'Contrato no encontrado'});
 const brand=getBrand(h.empresa_id); if(!brand)return res.status(404).json({error:'Empresa no encontrada'});
 const rows=[
  {Campo:'Cliente',Valor:h.razon_social||h.nombre_comercial||h.cliente||'—'},
  {Campo:'Título',Valor:h.titulo||'—'},
  {Campo:'Cotización',Valor:h.cotizacion_codigo||'—'},
  {Campo:'Suscripción',Valor:h.suscripcion_codigo||'—'},
  {Campo:'Vigencia',Valor:`${h.fecha_inicio||'—'} → ${h.fecha_fin||'Indefinida'}`},
  {Campo:'Estado',Valor:h.estado||'—'},
  {Campo:'Valor',Valor:Number(h.valor||0).toLocaleString('es-CO',{style:'currency',currency:brand.moneda||'COP',maximumFractionDigits:0})},
  {Campo:'Observaciones',Valor:h.observaciones||'—'}
 ];
 const pdf=buildPdf({title:`Contrato ${h.codigo}`,columns:['Campo','Valor'],rows,brand:{...brand,encabezado:'Documento contractual · Datos y condiciones principales',texto_legal:brand.terminos_condiciones||brand.texto_legal}});
 res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`attachment; filename="${h.codigo||`contrato-${id}`}.pdf"`);res.end(pdf);
});

r.get('/:id',requireAuth,requirePermission('contratos.ver'),(req,res)=>{const x=row(Number(req.params.id));if(!allowed(req,x))return res.status(404).json({error:'Contrato no encontrado'});res.json({contrato:x})});
r.post('/',requireAuth,requirePermission('contratos.crear'),(req,res)=>{const e=admin(req.user)&&Number(req.body.empresa_id)?Number(req.body.empresa_id):req.user.empresa_id,cliente=db.prepare('SELECT * FROM clientes WHERE id=? AND empresa_id=? AND estado=1').get(Number(req.body.cliente_id||0),e);if(!cliente)return res.status(400).json({error:'El cliente seleccionado no es válido.'});const qid=Number(req.body.cotizacion_id||0)||null,sid=Number(req.body.suscripcion_id||0)||null;if(!qid)return res.status(400).json({error:'El contrato debe estar asociado a una cotización Aceptada.'});const q=db.prepare("SELECT id,cliente_id,estado,total,subtotal,descuento,impuestos FROM cotizaciones WHERE id=? AND empresa_id=?").get(qid,e);if(!q||q.cliente_id!==cliente.id||q.estado!=='Aceptada')return res.status(409).json({error:'La cotización debe estar Aceptada y pertenecer al cliente.'});if(sid){const s=db.prepare("SELECT id,cliente_id,estado FROM suscripciones WHERE id=? AND empresa_id=?").get(sid,e);if(!s||s.cliente_id!==cliente.id||s.estado!=='Activa')return res.status(409).json({error:'La suscripción debe estar Activa y pertenecer al cliente.'})}if(sid&&db.prepare("SELECT id,codigo FROM contratos WHERE suscripcion_id=? AND estado IN ('Borrador','Activo')").get(sid))return res.status(409).json({error:'La suscripción ya tiene un contrato vigente o en borrador.'});const fi=String(req.body.fecha_inicio||'').trim(),ff=String(req.body.fecha_fin||'').trim();if(!fi)return res.status(400).json({error:'La fecha de inicio es obligatoria.'});if(ff&&ff<fi)return res.status(400).json({error:'La fecha de fin no puede ser anterior al inicio.'});const titulo=String(req.body.titulo||'').trim()||`Contrato ${cliente.razon_social||cliente.nombre_comercial||cliente.nombre}`;const valor=Math.max(0,Number(q.total||0));try{const x=db.prepare('INSERT INTO contratos(empresa_id,cliente_id,cotizacion_id,suscripcion_id,codigo,titulo,fecha_inicio,fecha_fin,estado,valor,observaciones,creado_por) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(e,cliente.id,qid,sid,nextCode(e),titulo,fi,ff,String(req.body.estado||'Borrador'),valor,String(req.body.observaciones||''),req.user.id);const id=Number(x.lastInsertRowid),codigo=row(id).codigo;try{db.pragma('wal_checkpoint(PASSIVE)')}catch{};audit(req,'CREAR',`Creó contrato ${codigo}`,e);res.status(201).json({ok:true,id,codigo,contrato:row(id)})}catch(err){res.status(400).json({error:err.message||'No fue posible crear el contrato.'})}});
r.put('/:id',requireAuth,requirePermission('contratos.editar'),(req,res)=>{const id=Number(req.params.id),cur=row(id);if(!allowed(req,cur))return res.status(404).json({error:'Contrato no encontrado'});if(cur.estado==='Activo')return res.status(409).json({error:'Un contrato Activo no puede editarse.'});const fi=String(req.body.fecha_inicio||cur.fecha_inicio),ff=String(req.body.fecha_fin||'');if(ff&&ff<fi)return res.status(400).json({error:'La fecha de fin no puede ser anterior al inicio.'});db.prepare('UPDATE contratos SET titulo=?,fecha_inicio=?,fecha_fin=?,estado=?,valor=?,observaciones=?,fecha_actualizacion=CURRENT_TIMESTAMP WHERE id=?').run(String(req.body.titulo||cur.titulo),fi,ff,String(req.body.estado||cur.estado),Math.max(0,Number(req.body.valor??cur.valor)),String(req.body.observaciones||''),id);audit(req,'EDITAR',`Editó contrato ${cur.codigo}`,cur.empresa_id);res.json({ok:true,contrato:row(id)})});
r.patch('/:id/estado',requireAuth,requirePermission('contratos.editar'),(req,res)=>{const id=Number(req.params.id),cur=row(id);if(!allowed(req,cur))return res.status(404).json({error:'Contrato no encontrado'});const estados=['Borrador','Activo','Suspendido','Vencido','Terminado','Anulado'],estado=String(req.body.estado||'');if(!estados.includes(estado))return res.status(400).json({error:'Estado de contrato no válido'});if(cur.estado==='Anulado'||cur.estado==='Terminado')return res.status(409).json({error:'El contrato está cerrado y no puede cambiar de estado.'});db.prepare('UPDATE contratos SET estado=?,fecha_actualizacion=CURRENT_TIMESTAMP WHERE id=?').run(estado,id);audit(req,'CAMBIAR_ESTADO',`Cambió ${cur.codigo} a ${estado}`,cur.empresa_id);res.json({ok:true,estado})});
r.delete('/:id',requireAuth,requirePermission('contratos.eliminar'),(req,res)=>{const id=Number(req.params.id),cur=row(id);if(!allowed(req,cur))return res.status(404).json({error:'Contrato no encontrado'});if(cur.estado==='Activo')return res.status(409).json({error:'Un contrato Activo no puede eliminarse.'});db.prepare('UPDATE contratos SET estado=\'Anulado\',fecha_actualizacion=CURRENT_TIMESTAMP WHERE id=?').run(id);audit(req,'ANULAR',`Anuló contrato ${cur.codigo}`,cur.empresa_id);res.json({ok:true})});
export default r;
