import { Router } from "express";
import { db } from "../db/database.js";
import { requireAuth, requirePermission } from "../middleware/auth.js";

const r = Router();
const isAdmin = u => u.rol === "Administrador";
const company = id => db.prepare("SELECT id,nombre,nit FROM empresas WHERE id=? AND estado=1").get(id);
function scopedCompany(req, requested=0){ return isAdmin(req.user) && Number(requested) ? Number(requested) : req.user.empresa_id; }
function audit(req, accion, detalle, empresaId){ db.prepare("INSERT INTO auditoria(empresa_id,usuario_id,accion,modulo,detalle,ip,resultado,metodo,ruta,user_agent) VALUES(?,?,?,?,?,?,?,?,?,?)").run(empresaId,req.user.id,accion,"M2M",detalle,req.ip,"OK",req.method,req.originalUrl,req.get("user-agent")||""); }

r.get("/resumen", requireAuth, requirePermission("m2m.ver"), (req,res)=>{
  const empresaId=scopedCompany(req,req.query.empresa_id); if(!company(empresaId)) return res.status(400).json({error:"Empresa no válida o inactiva"});
  const activos=db.prepare("SELECT COUNT(*) n FROM sim_cards WHERE empresa_id=? AND estado IN ('Disponible','Asignada','Activa')").get(empresaId).n;
  const suspendidas=db.prepare("SELECT COUNT(*) n FROM sim_cards WHERE empresa_id=? AND estado='Suspendida'").get(empresaId).n;
  const bajas=db.prepare("SELECT COUNT(*) n FROM sim_cards WHERE empresa_id=? AND estado='Baja'").get(empresaId).n;
  const consumo=db.prepare("SELECT COALESCE(SUM(c.mb_consumidos),0) mb FROM m2m_consumos c JOIN sim_cards s ON s.id=c.sim_id WHERE s.empresa_id=? AND c.periodo=date('now','start of month')").get(empresaId).mb;
  const planes=db.prepare("SELECT COUNT(*) n FROM m2m_planes WHERE empresa_id=? AND estado=1").get(empresaId).n;
  const alertas=db.prepare("SELECT COUNT(*) n FROM m2m_alertas WHERE empresa_id=? AND estado='ABIERTA'").get(empresaId).n;
  res.json({empresa_id:empresaId,kpis:{lineas_activas:activos,suspendidas,bajas,consumo_mb:Number(consumo||0),planes,alertas}});
});

r.get("/lineas", requireAuth, requirePermission("m2m.ver"), (req,res)=>{const empresaId=scopedCompany(req,req.query.empresa_id);if(!company(empresaId))return res.status(400).json({error:"Empresa no válida"});const rows=db.prepare(`SELECT s.id,s.empresa_id,s.iccid,s.numero,s.operador,s.estado,s.plan_id,s.fecha_corte,p.nombre plan_nombre,p.mb_incluidos,p.costo_mensual,g.imei,g.codigo equipo_codigo,a.placa,c.nombre cliente,COALESCE(SUM(CASE WHEN cns.periodo=strftime('%Y-%m','now') THEN cns.mb_consumidos ELSE 0 END),0) consumo_mes FROM sim_cards s LEFT JOIN m2m_planes p ON p.id=s.plan_id LEFT JOIN equipos g ON g.id=s.equipo_id LEFT JOIN activos a ON a.id=g.activo_id LEFT JOIN clientes c ON c.id=a.cliente_id LEFT JOIN m2m_consumos cns ON cns.sim_id=s.id WHERE s.empresa_id=? GROUP BY s.id ORDER BY s.iccid`).all(empresaId);res.json({lineas:rows})});
r.put("/lineas/:id", requireAuth, requirePermission("m2m.editar"), (req,res)=>{const id=Number(req.params.id),cur=db.prepare("SELECT * FROM sim_cards WHERE id=?").get(id);if(!cur||(!isAdmin(req.user)&&cur.empresa_id!==req.user.empresa_id))return res.status(404).json({error:"SIM no encontrada"});const planId=Number(req.body?.plan_id||0)||null,fechaCorte=req.body?.fecha_corte?Math.min(31,Math.max(1,Number(req.body.fecha_corte))):null;if(planId){const plan=db.prepare("SELECT id FROM m2m_planes WHERE id=? AND empresa_id=? AND estado=1").get(planId,cur.empresa_id);if(!plan)return res.status(400).json({error:"Plan M2M no válido para la empresa"})}db.prepare("UPDATE sim_cards SET plan_id=?,fecha_corte=?,fecha_actualizacion=CURRENT_TIMESTAMP WHERE id=?").run(planId,fechaCorte,id);audit(req,"ASIGNAR_PLAN",`Asignó plan M2M ${planId||"sin plan"} a SIM ${cur.iccid}`,cur.empresa_id);res.json({ok:true})});
r.patch("/lineas/:id/estado", requireAuth, requirePermission("m2m.editar"), (req,res)=>{const id=Number(req.params.id),cur=db.prepare("SELECT * FROM sim_cards WHERE id=?").get(id);if(!cur||(!isAdmin(req.user)&&cur.empresa_id!==req.user.empresa_id))return res.status(404).json({error:"SIM no encontrada"});const estados=["En inventario","Disponible","Asignada","Activa","Suspendida","Baja"],nuevo=String(req.body?.estado||"").trim(),motivo=String(req.body?.motivo||"").trim();if(!estados.includes(nuevo))return res.status(400).json({error:"Estado M2M no válido"});if(nuevo===cur.estado)return res.json({ok:true});db.prepare("UPDATE sim_cards SET estado=?,fecha_suspension=CASE WHEN ?='Suspendida' THEN COALESCE(NULLIF(fecha_suspension,''),date('now')) ELSE fecha_suspension END,fecha_baja=CASE WHEN ?='Baja' THEN COALESCE(NULLIF(fecha_baja,''),date('now')) ELSE fecha_baja END,fecha_actualizacion=CURRENT_TIMESTAMP WHERE id=?").run(nuevo,nuevo,nuevo,id);db.prepare("INSERT INTO m2m_historial_estados(empresa_id,sim_id,estado_anterior,estado_nuevo,motivo,usuario_id) VALUES(?,?,?,?,?,?)").run(cur.empresa_id,id,cur.estado,nuevo,motivo,req.user.id);audit(req,"CAMBIO_ESTADO",`SIM ${cur.iccid}: ${cur.estado} → ${nuevo}`,cur.empresa_id);res.json({ok:true})});

r.get("/planes", requireAuth, requirePermission("m2m.ver"), (req,res)=>{
  const empresaId=scopedCompany(req,req.query.empresa_id); if(!company(empresaId)) return res.status(400).json({error:"Empresa no válida o inactiva"});
  const rows=db.prepare("SELECT p.*,e.nombre empresa FROM m2m_planes p JOIN empresas e ON e.id=p.empresa_id WHERE p.empresa_id=? ORDER BY p.nombre").all(empresaId);
  res.json({planes:rows,empresas:isAdmin(req.user)?db.prepare("SELECT id,nombre,nit FROM empresas WHERE estado=1 ORDER BY nombre").all():[company(empresaId)]});
});

function normalizePlan(b={}){return {nombre:String(b.nombre||"").trim(),operador:String(b.operador||"").trim(),descripcion:String(b.descripcion||"").trim(),mb_incluidos:Number(b.mb_incluidos||0),costo_mensual:Number(b.costo_mensual||0),dia_corte:Math.min(31,Math.max(1,Number(b.dia_corte||1))),alerta_80:Number(b.alerta_80??80),alerta_100:Number(b.alerta_100??100),estado:Number(b.estado??1)}}

r.post("/planes", requireAuth, requirePermission("m2m.crear"), (req,res)=>{const d=normalizePlan(req.body),empresaId=scopedCompany(req,req.body?.empresa_id);if(!company(empresaId))return res.status(400).json({error:"Empresa no válida"});if(!d.nombre)return res.status(400).json({error:"Ingrese el nombre del plan"});const x=db.prepare("INSERT INTO m2m_planes(empresa_id,nombre,operador,descripcion,mb_incluidos,costo_mensual,dia_corte,alerta_80,alerta_100,estado,creado_por) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(empresaId,d.nombre,d.operador,d.descripcion,d.mb_incluidos,d.costo_mensual,d.dia_corte,d.alerta_80,d.alerta_100,d.estado,req.user.id);audit(req,"CREAR_PLAN",`Creó plan M2M ${d.nombre}`,empresaId);res.status(201).json({ok:true,id:Number(x.lastInsertRowid)})});
r.put("/planes/:id", requireAuth, requirePermission("m2m.editar"), (req,res)=>{const id=Number(req.params.id),cur=db.prepare("SELECT * FROM m2m_planes WHERE id=?").get(id);if(!cur||(!isAdmin(req.user)&&cur.empresa_id!==req.user.empresa_id))return res.status(404).json({error:"Plan no encontrado"});const d=normalizePlan(req.body);if(!d.nombre)return res.status(400).json({error:"Ingrese el nombre del plan"});db.prepare("UPDATE m2m_planes SET nombre=?,operador=?,descripcion=?,mb_incluidos=?,costo_mensual=?,dia_corte=?,alerta_80=?,alerta_100=?,estado=?,fecha_actualizacion=CURRENT_TIMESTAMP WHERE id=?").run(d.nombre,d.operador,d.descripcion,d.mb_incluidos,d.costo_mensual,d.dia_corte,d.alerta_80,d.alerta_100,d.estado,id);audit(req,"EDITAR_PLAN",`Editó plan M2M ${d.nombre}`,cur.empresa_id);res.json({ok:true})});
r.delete("/planes/:id", requireAuth, requirePermission("m2m.eliminar"), (req,res)=>{const id=Number(req.params.id),cur=db.prepare("SELECT * FROM m2m_planes WHERE id=?").get(id);if(!cur||(!isAdmin(req.user)&&cur.empresa_id!==req.user.empresa_id))return res.status(404).json({error:"Plan no encontrado"});db.prepare("UPDATE m2m_planes SET estado=0,fecha_actualizacion=CURRENT_TIMESTAMP WHERE id=?").run(id);audit(req,"BAJA_PLAN",`Desactivó plan M2M ${cur.nombre}`,cur.empresa_id);res.json({ok:true})});

r.get("/consumos", requireAuth, requirePermission("m2m.ver"), (req,res)=>{const empresaId=scopedCompany(req,req.query.empresa_id),periodo=String(req.query.periodo||new Date().toISOString().slice(0,7));if(!company(empresaId))return res.status(400).json({error:"Empresa no válida"});const rows=db.prepare(`SELECT c.*,s.iccid,s.numero,s.operador,s.plan_m2m,s.estado sim_estado,g.imei,g.imei equipo_codigo,a.placa,cl.nombre cliente,p.nombre plan_nombre,p.mb_incluidos,p.alerta_80,p.alerta_100 FROM m2m_consumos c JOIN sim_cards s ON s.id=c.sim_id LEFT JOIN equipos g ON g.id=s.equipo_id LEFT JOIN activos a ON a.id=g.activo_id LEFT JOIN clientes cl ON cl.id=a.cliente_id LEFT JOIN m2m_planes p ON p.id=s.plan_id WHERE s.empresa_id=? AND c.periodo=? ORDER BY c.mb_consumidos DESC`).all(empresaId,periodo);res.json({consumos:rows,periodo})});
r.post("/consumos", requireAuth, requirePermission("m2m.editar"), (req,res)=>{const simId=Number(req.body?.sim_id),periodo=String(req.body?.periodo||new Date().toISOString().slice(0,7)).slice(0,7),mb=Math.max(0,Number(req.body?.mb_consumidos||0));const sim=db.prepare("SELECT * FROM sim_cards WHERE id=?").get(simId);if(!sim||(!isAdmin(req.user)&&sim.empresa_id!==req.user.empresa_id))return res.status(404).json({error:"SIM no encontrada"});db.prepare("INSERT INTO m2m_consumos(sim_id,periodo,mb_consumidos,fecha_actualizacion) VALUES(?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(sim_id,periodo) DO UPDATE SET mb_consumidos=excluded.mb_consumidos,fecha_actualizacion=CURRENT_TIMESTAMP").run(simId,periodo,mb);const plan=sim.plan_id?db.prepare("SELECT * FROM m2m_planes WHERE id=?").get(sim.plan_id):null;if(plan&&plan.mb_incluidos>0){const pct=mb/plan.mb_incluidos*100;const tipo=pct>=plan.alerta_100?"CONSUMO_100":pct>=plan.alerta_80?"CONSUMO_80":null;if(tipo){const existe=db.prepare("SELECT id FROM m2m_alertas WHERE sim_id=? AND tipo=? AND periodo=? AND estado='ABIERTA'").get(simId,tipo,periodo);if(!existe){db.prepare("INSERT INTO m2m_alertas(empresa_id,sim_id,tipo,periodo,umbral,mensaje,estado) VALUES(?,?,?,?,?,?,?)").run(sim.empresa_id,simId,tipo,periodo,pct,`Consumo M2M ${pct.toFixed(1)}% del plan`,"ABIERTA")}}}audit(req,"ACTUALIZAR_CONSUMO",`Actualizó consumo SIM ${sim.iccid}: ${mb} MB (${periodo})`,sim.empresa_id);res.json({ok:true})});

r.get("/alertas", requireAuth, requirePermission("m2m.ver"), (req,res)=>{const empresaId=scopedCompany(req,req.query.empresa_id);if(!company(empresaId))return res.status(400).json({error:"Empresa no válida"});const rows=db.prepare(`SELECT a.*,s.iccid,s.numero,s.operador,g.imei FROM m2m_alertas a JOIN sim_cards s ON s.id=a.sim_id LEFT JOIN equipos g ON g.id=s.equipo_id WHERE a.empresa_id=? ORDER BY CASE WHEN a.estado='ABIERTA' THEN 0 ELSE 1 END,a.fecha_creacion DESC LIMIT 500`).all(empresaId);res.json({alertas:rows})});
r.patch("/alertas/:id", requireAuth, requirePermission("m2m.editar"), (req,res)=>{const id=Number(req.params.id),cur=db.prepare("SELECT * FROM m2m_alertas WHERE id=?").get(id);if(!cur||(!isAdmin(req.user)&&cur.empresa_id!==req.user.empresa_id))return res.status(404).json({error:"Alerta no encontrada"});const estado=String(req.body?.estado||"ATENDIDA");db.prepare("UPDATE m2m_alertas SET estado=?,fecha_atencion=CURRENT_TIMESTAMP,atendida_por=? WHERE id=?").run(estado,req.user.id,id);audit(req,"ATENDER_ALERTA",`Actualizó alerta M2M ${id} a ${estado}`,cur.empresa_id);res.json({ok:true})});

r.get("/historial", requireAuth, requirePermission("m2m.ver"), (req,res)=>{const empresaId=scopedCompany(req,req.query.empresa_id);if(!company(empresaId))return res.status(400).json({error:"Empresa no válida"});const rows=db.prepare(`SELECT h.*,s.iccid,s.numero,u.nombre usuario_nombre,u.apellido usuario_apellido FROM m2m_historial_estados h JOIN sim_cards s ON s.id=h.sim_id LEFT JOIN usuarios u ON u.id=h.usuario_id WHERE h.empresa_id=? ORDER BY h.fecha DESC LIMIT 500`).all(empresaId);res.json({historial:rows})});

export default r;
