import { Router } from "express";
import { db } from "../db/database.js";
import { requireAuth, requirePermission } from "../middleware/auth.js";
const r=Router(); const admin=u=>u.rol==="Administrador";
function audit(req,a,d,e=req.user.empresa_id){db.prepare("INSERT INTO auditoria(empresa_id,usuario_id,accion,modulo,detalle,ip,resultado,metodo,ruta,user_agent) VALUES(?,?,?,?,?,?,?,?,?,?)").run(e,req.user.id,a,"PROSPECTOS",d,req.ip,"OK",req.method,req.originalUrl,req.get("user-agent")||"")}
function norm(b={}){return {codigo:String(b.codigo||"").trim(),nombre:String(b.nombre||"").trim(),tipo_prospecto:String(b.tipo_prospecto||"Empresa").trim(),nit:String(b.nit||"").trim(),contacto:String(b.contacto||"").trim(),telefono:String(b.telefono||"").trim(),correo:String(b.correo||"").trim().toLowerCase(),ciudad:String(b.ciudad||"").trim(),direccion:String(b.direccion||"").trim(),origen:String(b.origen||"Otro").trim(),etapa:String(b.etapa||"Nuevo").trim(),estado:Number(b.estado)?1:0,proxima_gestion:String(b.proxima_gestion||"").trim(),observaciones:String(b.observaciones||"").trim()}}
function get(id){return db.prepare(`SELECT p.*,e.nombre empresa,COALESCE(u.nombre||' '||u.apellido,'') responsable FROM prospectos p JOIN empresas e ON e.id=p.empresa_id LEFT JOIN usuarios u ON u.id=p.responsable_id WHERE p.id=?`).get(id)}
function scope(req){const q=String(req.query.q||"").trim(),etapa=String(req.query.etapa||"").trim(),estado=req.query.estado==="0"?0:req.query.estado==="1"?1:null,requested=Number(req.query.empresa_id||0),eid=admin(req.user)&&requested?requested:req.user.empresa_id;let w=" WHERE p.empresa_id=?",ps=[eid];if(q){w+=" AND (p.codigo LIKE ? OR p.nombre LIKE ? OR p.nit LIKE ? OR p.contacto LIKE ? OR p.telefono LIKE ? OR p.correo LIKE ? OR p.ciudad LIKE ?)";const x=`%${q}%`;ps.push(x,x,x,x,x,x,x)}if(etapa){w+=" AND p.etapa=?";ps.push(etapa)}if(estado!==null){w+=" AND p.estado=?";ps.push(estado)}return {w,ps,eid}}
r.get("/export",requireAuth,requirePermission("prospectos.exportar"),(req,res)=>{const {w,ps}=scope(req);const rows=db.prepare(`SELECT p.codigo,p.nombre,p.tipo_prospecto,p.nit,p.contacto,p.telefono,p.correo,p.ciudad,p.direccion,p.origen,p.etapa,CASE WHEN p.estado=1 THEN 'Activo' ELSE 'Inactivo' END estado,p.proxima_gestion,p.observaciones,e.nombre empresa,p.fecha_creacion FROM prospectos p JOIN empresas e ON e.id=p.empresa_id${w} ORDER BY p.nombre`).all(...ps);const h=["codigo","nombre","tipo_prospecto","nit","contacto","telefono","correo","ciudad","direccion","origen","etapa","estado","proxima_gestion","observaciones","empresa","fecha_creacion"];const c=v=>`"${String(v??"").replaceAll('"','""')}"`;const csv=[h.join(","),...rows.map(x=>h.map(k=>c(x[k])).join(","))].join("\n");res.setHeader("Content-Type","text/csv; charset=utf-8");res.setHeader("Content-Disposition",`attachment; filename="prospectos-itgps-${new Date().toISOString().slice(0,10)}.csv"`);res.send("\ufeff"+csv)})
r.get("/",requireAuth,requirePermission("prospectos.ver"),(req,res)=>{const {w,ps}=scope(req);res.json({prospectos:db.prepare(`SELECT p.*,e.nombre empresa,COALESCE(u.nombre||' '||u.apellido,'') responsable FROM prospectos p JOIN empresas e ON e.id=p.empresa_id LEFT JOIN usuarios u ON u.id=p.responsable_id${w} ORDER BY p.nombre LIMIT 1000`).all(...ps)})})
r.get("/:id",requireAuth,requirePermission("prospectos.ver"),(req,res)=>{const p=get(Number(req.params.id));if(!p||(!admin(req.user)&&p.empresa_id!==req.user.empresa_id))return res.status(404).json({error:"Prospecto no encontrado"});res.json({prospecto:p})})
r.post("/",requireAuth,requirePermission("prospectos.crear"),(req,res)=>{const d=norm(req.body);if(!d.nombre)return res.status(400).json({error:"Nombre del prospecto obligatorio"});const eid=admin(req.user)&&Number(req.body.empresa_id)?Number(req.body.empresa_id):req.user.empresa_id;if(!db.prepare("SELECT id FROM empresas WHERE id=? AND estado=1").get(eid))return res.status(400).json({error:"Empresa no válida o inactiva"});const max=db.prepare("SELECT codigo FROM prospectos WHERE empresa_id=? AND codigo<>''").all(eid);let n=0;for(const row of max){const m=String(row.codigo||"").match(/^PRO-?(\d+)$/i);if(m)n=Math.max(n,Number(m[1]));}const codigo=`PRO${String(n+1).padStart(4,"0")}`;const x=db.prepare(`INSERT INTO prospectos(empresa_id,codigo,nombre,tipo_prospecto,nit,contacto,telefono,correo,ciudad,direccion,origen,etapa,estado,proxima_gestion,observaciones,creado_por,fecha_actualizacion) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)`).run(eid,codigo,d.nombre,d.tipo_prospecto,d.nit,d.contacto,d.telefono,d.correo,d.ciudad,d.direccion,d.origen,d.etapa,d.estado,d.proxima_gestion,d.observaciones,req.user.id);audit(req,"CREAR",`Creó prospecto ${d.nombre}`,eid);res.status(201).json({ok:true,id:Number(x.lastInsertRowid)})})
r.put("/:id",requireAuth,requirePermission("prospectos.editar"),(req,res)=>{const id=Number(req.params.id),p=get(id);if(!p||(!admin(req.user)&&p.empresa_id!==req.user.empresa_id))return res.status(404).json({error:"Prospecto no encontrado"});const d=norm(req.body),eid=admin(req.user)&&Number(req.body.empresa_id)?Number(req.body.empresa_id):p.empresa_id;if(!d.nombre)return res.status(400).json({error:"Nombre del prospecto obligatorio"});db.prepare(`UPDATE prospectos SET empresa_id=?,codigo=?,nombre=?,tipo_prospecto=?,nit=?,contacto=?,telefono=?,correo=?,ciudad=?,direccion=?,origen=?,etapa=?,estado=?,proxima_gestion=?,observaciones=?,fecha_actualizacion=CURRENT_TIMESTAMP WHERE id=?`).run(eid,d.codigo,d.nombre,d.tipo_prospecto,d.nit,d.contacto,d.telefono,d.correo,d.ciudad,d.direccion,d.origen,d.etapa,d.estado,d.proxima_gestion,d.observaciones,id);audit(req,"EDITAR",`Editó prospecto ${id} - ${d.nombre}`,eid);res.json({ok:true})})
r.delete("/:id",requireAuth,requirePermission("prospectos.eliminar"),(req,res)=>{const id=Number(req.params.id),p=get(id);if(!p||(!admin(req.user)&&p.empresa_id!==req.user.empresa_id))return res.status(404).json({error:"Prospecto no encontrado"});db.prepare("DELETE FROM prospectos WHERE id=?").run(id);audit(req,"ELIMINAR",`Eliminó prospecto ${id} - ${p.nombre}`,p.empresa_id);res.json({ok:true})})
r.post("/:id/convertir",requireAuth,requirePermission("prospectos.editar"),(req,res)=>{const id=Number(req.params.id),p=get(id);if(!p||(!admin(req.user)&&p.empresa_id!==req.user.empresa_id))return res.status(404).json({error:"Prospecto no encontrado"});if(p.convertido_cliente_id)return res.status(409).json({error:"El prospecto ya fue convertido"});const x=db.prepare(`INSERT INTO clientes(empresa_id,codigo,nombre,nit,tipo_cliente,contacto,telefono,correo,direccion,ciudad,estado,observaciones,creado_por,fecha_actualizacion) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)`).run(p.empresa_id,p.codigo,p.nombre,p.nit,p.tipo_prospecto,p.contacto,p.telefono,p.correo,p.direccion,p.ciudad,1,p.observaciones,req.user.id);db.prepare("UPDATE prospectos SET convertido_cliente_id=?,etapa='Ganado',estado=0,fecha_actualizacion=CURRENT_TIMESTAMP WHERE id=?").run(Number(x.lastInsertRowid),id);db.prepare("UPDATE cotizaciones SET cliente_id=? WHERE prospecto_id=? AND cliente_id IS NULL").run(Number(x.lastInsertRowid),id);audit(req,"CONVERTIR",`Convirtió prospecto ${p.nombre} en cliente ${Number(x.lastInsertRowid)}`,p.empresa_id);res.json({ok:true,cliente_id:Number(x.lastInsertRowid)})})
export default r;
