import { Router } from "express";
import { db } from "../db/database.js";
import { requireAuth, requirePermission } from "../middleware/auth.js";
const r=Router();
function audit(q,accion,detalle){db.prepare("INSERT INTO auditoria(empresa_id,usuario_id,accion,modulo,detalle,ip,resultado,metodo,ruta,user_agent) VALUES(?,?,?,?,?,?,?,?,?,?)").run(q.user.empresa_id,q.user.id,accion,"ROLES",detalle,q.ip,"OK",q.method,q.originalUrl,q.get("user-agent")||"");}
function role(id){return db.prepare("SELECT id,nombre,estado,fecha_creacion FROM roles WHERE id=?").get(id);}
r.get("/",requireAuth,requirePermission("roles.ver"),(q,s)=>s.json({roles:db.prepare("SELECT id,nombre,estado,fecha_creacion FROM roles ORDER BY nombre").all()}));
r.get("/catalogo/permisos",requireAuth,requirePermission("roles.ver"),(q,s)=>s.json({permisos:db.prepare("SELECT id,codigo,nombre,modulo,accion FROM permisos ORDER BY modulo,CASE accion WHEN 'ver' THEN 1 WHEN 'crear' THEN 2 WHEN 'editar' THEN 3 WHEN 'eliminar' THEN 4 ELSE 5 END").all()}));
r.get("/:id",requireAuth,requirePermission("roles.ver"),(q,s)=>{const x=role(Number(q.params.id));if(!x)return s.status(404).json({error:"Rol no encontrado"});const permisos=db.prepare("SELECT p.id,p.codigo,p.nombre,p.modulo,p.accion FROM permisos p JOIN rol_permisos rp ON rp.permiso_id=p.id WHERE rp.rol_id=? ORDER BY p.modulo,p.accion").all(x.id);s.json({rol:x,permisos});});
r.post("/",requireAuth,requirePermission("roles.crear"),(q,s)=>{const nombre=q.body?.nombre?.trim();if(!nombre)return s.status(400).json({error:"Nombre del rol obligatorio"});try{const id=db.prepare("INSERT INTO roles(nombre) VALUES(?)").run(nombre).lastInsertRowid;audit(q,"CREAR",`Creó rol ${nombre}`);return s.status(201).json({ok:true,id:Number(id)});}catch{return s.status(409).json({error:"El rol ya existe"});}});
r.put("/:id",requireAuth,requirePermission("roles.editar"),(q,s)=>{const id=Number(q.params.id),nombre=q.body?.nombre?.trim(),estado=q.body?.estado?1:0;if(!nombre)return s.status(400).json({error:"Nombre del rol obligatorio"});const x=role(id);if(!x)return s.status(404).json({error:"Rol no encontrado"});if(x.nombre==="Administrador"&&estado===0)return s.status(400).json({error:"El rol Administrador no puede desactivarse"});try{db.prepare("UPDATE roles SET nombre=?,estado=? WHERE id=?").run(nombre,estado,id);audit(q,"EDITAR",`Editó rol ${id}`);s.json({ok:true});}catch{s.status(409).json({error:"El rol ya existe"});}});
r.put("/:id/permisos",requireAuth,requirePermission("roles.editar"),(q,s)=>{const id=Number(q.params.id),permisos=Array.isArray(q.body?.permisos)?q.body.permisos.map(Number):[];const x=role(id);if(!x)return s.status(404).json({error:"Rol no encontrado"});const tx=db.transaction(()=>{db.prepare("DELETE FROM rol_permisos WHERE rol_id=?").run(id);const ins=db.prepare("INSERT OR IGNORE INTO rol_permisos(rol_id,permiso_id) VALUES(?,?)");for(const p of permisos)ins.run(id,p);});tx();audit(q,"PERMISOS",`Actualizó permisos del rol ${x.nombre}`);s.json({ok:true});});
export default r;
