import { Router } from "express";
import { db } from "../db/database.js";
import { requireAuth, requirePermission } from "../middleware/auth.js";

const r=Router();
const isAdmin=u=>u.rol==="Administrador";
const company=id=>db.prepare("SELECT id,nombre,nit FROM empresas WHERE id=? AND estado=1").get(id);
function getSim(id){return db.prepare(`SELECT s.*,e.nombre empresa,g.imei equipo_imei,g.codigo equipo_codigo,g.marca equipo_marca,g.modelo equipo_modelo,a.id activo_id,a.codigo activo_codigo,a.placa,c.nombre cliente FROM sim_cards s JOIN empresas e ON e.id=s.empresa_id LEFT JOIN equipos g ON g.id=s.equipo_id LEFT JOIN activos a ON a.id=g.activo_id LEFT JOIN clientes c ON c.id=a.cliente_id WHERE s.id=?`).get(id)}
function audit(req,accion,detalle,empresaId){db.prepare("INSERT INTO auditoria(empresa_id,usuario_id,accion,modulo,detalle,ip,resultado,metodo,ruta,user_agent) VALUES(?,?,?,?,?,?,?,?,?,?)").run(empresaId,req.user.id,accion,"SIM",detalle,req.ip,"OK",req.method,req.originalUrl,req.get("user-agent")||"")}
function catalogs(req,res){const requested=Number(req.query.empresa_id||0),empresaId=isAdmin(req.user)?requested:req.user.empresa_id;if(isAdmin(req.user)&&!empresaId)return res.json({empresas:db.prepare("SELECT id,nombre,nit FROM empresas WHERE estado=1 ORDER BY nombre").all(),equipos:[]});if(!company(empresaId))return res.status(400).json({error:"Empresa no válida o inactiva"});const empresas=isAdmin(req.user)?db.prepare("SELECT id,nombre,nit FROM empresas WHERE estado=1 ORDER BY nombre").all():[company(empresaId)];const equipos=db.prepare(`SELECT g.id,g.imei,g.codigo,g.marca,g.modelo,g.estado,a.codigo activo_codigo,a.placa,c.nombre cliente FROM equipos g LEFT JOIN activos a ON a.id=g.activo_id LEFT JOIN clientes c ON c.id=a.cliente_id WHERE g.empresa_id=? AND g.estado<>'Retirado' ORDER BY COALESCE(NULLIF(g.codigo,''),g.imei)`).all(empresaId);res.json({empresas,equipos})}
r.get("/catalogos",requireAuth,requirePermission("sim.ver"),catalogs);
r.get("/",requireAuth,requirePermission("sim.ver"),(req,res)=>{const requested=Number(req.query.empresa_id||0),empresaId=isAdmin(req.user)&&requested?requested:req.user.empresa_id,q=String(req.query.q||"").trim(),estado=String(req.query.estado||"").trim(),params=[empresaId];let sql=`SELECT s.id,s.empresa_id,s.equipo_id,s.iccid,s.imsi,s.numero,s.operador,s.plan_m2m,s.apn,s.usuario_apn,s.clave_apn,s.estado,s.fecha_activacion,s.fecha_suspension,s.fecha_baja,s.observaciones,e.nombre empresa,g.imei equipo_imei,g.codigo equipo_codigo,g.marca equipo_marca,g.modelo equipo_modelo,a.codigo activo_codigo,a.placa,c.nombre cliente FROM sim_cards s JOIN empresas e ON e.id=s.empresa_id LEFT JOIN equipos g ON g.id=s.equipo_id LEFT JOIN activos a ON a.id=g.activo_id LEFT JOIN clientes c ON c.id=a.cliente_id WHERE s.empresa_id=?`;if(q){sql+=` AND (s.iccid LIKE ? OR s.imsi LIKE ? OR s.numero LIKE ? OR s.operador LIKE ? OR s.plan_m2m LIKE ? OR s.apn LIKE ? OR g.imei LIKE ? OR g.codigo LIKE ? OR a.placa LIKE ? OR a.codigo LIKE ? OR c.nombre LIKE ?)`;const l=`%${q}%`;for(let i=0;i<11;i++)params.push(l)}if(estado){sql+=" AND s.estado=?";params.push(estado)}sql+=" ORDER BY s.iccid LIMIT 2000";res.json({sim_cards:db.prepare(sql).all(...params)})});
r.get("/export",requireAuth,requirePermission("sim.exportar"),(req,res)=>{const requested=Number(req.query.empresa_id||0),empresaId=isAdmin(req.user)&&requested?requested:req.user.empresa_id,q=String(req.query.q||"").trim(),estado=String(req.query.estado||"").trim(),params=[empresaId];let sql=`SELECT s.iccid,s.imsi,s.numero,s.operador,s.plan_m2m,s.apn,s.usuario_apn,s.estado,s.fecha_activacion,s.fecha_suspension,s.fecha_baja,e.nombre empresa,g.imei equipo_imei,g.codigo equipo_codigo,a.codigo activo_codigo,a.placa,c.nombre cliente,s.observaciones FROM sim_cards s JOIN empresas e ON e.id=s.empresa_id LEFT JOIN equipos g ON g.id=s.equipo_id LEFT JOIN activos a ON a.id=g.activo_id LEFT JOIN clientes c ON c.id=a.cliente_id WHERE s.empresa_id=?`;if(q){sql+=` AND (s.iccid LIKE ? OR s.imsi LIKE ? OR s.numero LIKE ? OR s.operador LIKE ? OR s.plan_m2m LIKE ? OR s.apn LIKE ? OR g.imei LIKE ? OR g.codigo LIKE ? OR a.placa LIKE ? OR a.codigo LIKE ? OR c.nombre LIKE ?)`;const l=`%${q}%`;for(let i=0;i<11;i++)params.push(l)}if(estado){sql+=" AND s.estado=?";params.push(estado)}const rows=db.prepare(sql+" ORDER BY s.iccid").all(...params),h=["iccid","imsi","numero","operador","plan_m2m","apn","usuario_apn","estado","fecha_activacion","fecha_suspension","fecha_baja","empresa","equipo_imei","equipo_codigo","activo_codigo","placa","cliente","observaciones"],cell=v=>`"${String(v??"").replaceAll('"','""')}"`,csv=[h.join(","),...rows.map(x=>h.map(k=>cell(x[k])).join(","))].join("\n");res.setHeader("Content-Type","text/csv; charset=utf-8");res.setHeader("Content-Disposition",`attachment; filename="tarjetas-sim-itgps-${new Date().toISOString().slice(0,10)}.csv"`);res.send("\ufeff"+csv)});
r.get("/:id",requireAuth,requirePermission("sim.ver"),(req,res)=>{const x=getSim(Number(req.params.id));if(!x)return res.status(404).json({error:"Tarjeta SIM no encontrada"});if(!isAdmin(req.user)&&x.empresa_id!==req.user.empresa_id)return res.status(404).json({error:"Tarjeta SIM no encontrada"});res.json({sim:x})});
function normalize(b={}){return {iccid:String(b.iccid||"").replace(/\s+/g,"").trim(),imsi:String(b.imsi||"").replace(/\s+/g,"").trim(),numero:String(b.numero||"").trim(),operador:String(b.operador||"").trim(),plan_m2m:String(b.plan_m2m||"").trim(),apn:String(b.apn||"").trim(),usuario_apn:String(b.usuario_apn||"").trim(),clave_apn:String(b.clave_apn||"").trim(),estado:String(b.estado||"En inventario").trim(),fecha_activacion:String(b.fecha_activacion||"").trim(),fecha_suspension:String(b.fecha_suspension||"").trim(),fecha_baja:String(b.fecha_baja||"").trim(),observaciones:String(b.observaciones||"").trim()}}
function validateAssignment(empresaId,equipoId,excludeId=0){const e=db.prepare("SELECT id,empresa_id,estado FROM equipos WHERE id=? AND empresa_id=?").get(equipoId,empresaId);if(!e||e.estado==="Retirado")return false;const assigned=db.prepare("SELECT id FROM sim_cards WHERE equipo_id=? AND estado<>'Baja' AND id<>? LIMIT 1").get(equipoId,excludeId);return !assigned}
r.post("/",requireAuth,requirePermission("sim.crear"),(req,res)=>{const d=normalize(req.body);if(!d.iccid||!/^[0-9]{10,22}$/.test(d.iccid))return res.status(400).json({error:"El ICCID debe contener entre 10 y 22 dígitos"});const empresaId=isAdmin(req.user)&&Number(req.body?.empresa_id)?Number(req.body.empresa_id):req.user.empresa_id;if(!company(empresaId))return res.status(400).json({error:"Empresa no válida o inactiva"});const equipoId=Number(req.body?.equipo_id||0)||null;if(equipoId&&!validateAssignment(empresaId,equipoId))return res.status(400).json({error:"El equipo GPS no es válido o ya tiene una SIM asignada"});if(db.prepare("SELECT id FROM sim_cards WHERE iccid=?").get(d.iccid))return res.status(409).json({error:"El ICCID ya está registrado"});if(d.imsi&&db.prepare("SELECT id FROM sim_cards WHERE imsi=?").get(d.imsi))return res.status(409).json({error:"El IMSI ya está registrado"});try{const x=db.prepare(`INSERT INTO sim_cards(empresa_id,equipo_id,iccid,imsi,numero,operador,plan_m2m,apn,usuario_apn,clave_apn,estado,fecha_activacion,fecha_suspension,fecha_baja,observaciones,creado_por) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(empresaId,equipoId,d.iccid,d.imsi,d.numero,d.operador,d.plan_m2m,d.apn,d.usuario_apn,d.clave_apn,d.estado,d.fecha_activacion,d.fecha_suspension,d.fecha_baja,d.observaciones,req.user.id);audit(req,"CREAR",`Creó tarjeta SIM ICCID ${d.iccid}`,empresaId);res.status(201).json({ok:true,id:Number(x.lastInsertRowid)})}catch(e){res.status(409).json({error:"No fue posible crear la tarjeta SIM"})}});
r.put("/:id",requireAuth,requirePermission("sim.editar"),(req,res)=>{const id=Number(req.params.id),cur=getSim(id);if(!cur)return res.status(404).json({error:"Tarjeta SIM no encontrada"});if(!isAdmin(req.user)&&cur.empresa_id!==req.user.empresa_id)return res.status(404).json({error:"Tarjeta SIM no encontrada"});const d=normalize(req.body);if(!d.iccid||!/^[0-9]{10,22}$/.test(d.iccid))return res.status(400).json({error:"El ICCID debe contener entre 10 y 22 dígitos"});const empresaId=isAdmin(req.user)&&Number(req.body?.empresa_id)?Number(req.body.empresa_id):cur.empresa_id;if(!company(empresaId))return res.status(400).json({error:"Empresa no válida o inactiva"});const equipoId=Number(req.body?.equipo_id||0)||null;if(equipoId&&!validateAssignment(empresaId,equipoId,id))return res.status(400).json({error:"El equipo GPS no es válido o ya tiene una SIM asignada"});if(db.prepare("SELECT id FROM sim_cards WHERE iccid=? AND id<>?").get(d.iccid,id))return res.status(409).json({error:"El ICCID ya está registrado en otra SIM"});if(d.imsi&&db.prepare("SELECT id FROM sim_cards WHERE imsi=? AND id<>?").get(d.imsi,id))return res.status(409).json({error:"El IMSI ya está registrado en otra SIM"});db.prepare(`UPDATE sim_cards SET empresa_id=?,equipo_id=?,iccid=?,imsi=?,numero=?,operador=?,plan_m2m=?,apn=?,usuario_apn=?,clave_apn=?,estado=?,fecha_activacion=?,fecha_suspension=?,fecha_baja=?,observaciones=?,fecha_actualizacion=CURRENT_TIMESTAMP WHERE id=?`).run(empresaId,equipoId,d.iccid,d.imsi,d.numero,d.operador,d.plan_m2m,d.apn,d.usuario_apn,d.clave_apn,d.estado,d.fecha_activacion,d.fecha_suspension,d.fecha_baja,d.observaciones,id);audit(req,"EDITAR",`Editó tarjeta SIM ID ${id} - ICCID ${d.iccid}`,empresaId);res.json({ok:true})});
r.delete("/:id",requireAuth,requirePermission("sim.eliminar"),(req,res)=>{const id=Number(req.params.id),cur=getSim(id);if(!cur)return res.status(404).json({error:"Tarjeta SIM no encontrada"});if(!isAdmin(req.user)&&cur.empresa_id!==req.user.empresa_id)return res.status(404).json({error:"Tarjeta SIM no encontrada"});db.prepare("UPDATE sim_cards SET estado='Baja',equipo_id=NULL,fecha_baja=COALESCE(NULLIF(fecha_baja,''),date('now')),fecha_actualizacion=CURRENT_TIMESTAMP WHERE id=?").run(id);audit(req,"BAJA",`Dio de baja tarjeta SIM ID ${id} - ICCID ${cur.iccid}`,cur.empresa_id);res.json({ok:true})});
export default r;
