import { Router } from "express";
import { db } from "../db/database.js";
import { requireAuth, requirePermission } from "../middleware/auth.js";
const r=Router(); const isAdmin=u=>u.rol==="Administrador";
function audit(req,accion,detalle,empresaId=req.user.empresa_id){db.prepare("INSERT INTO auditoria(empresa_id,usuario_id,accion,modulo,detalle,ip,resultado,metodo,ruta,user_agent) VALUES(?,?,?,?,?,?,?,?,?,?)").run(empresaId,req.user.id,accion,"SUSCRIPCIONES",detalle,req.ip,"OK",req.method,req.originalUrl,req.get("user-agent")||"")}
function row(id){return db.prepare(`SELECT s.*,c.nombre cliente,c.razon_social,c.nombre_comercial,p.nombre plan,p.codigo plan_codigo,sv.nombre servicio FROM suscripciones s JOIN clientes c ON c.id=s.cliente_id JOIN planes p ON p.id=s.plan_id JOIN servicios sv ON sv.id=p.servicio_id WHERE s.id=?`).get(id)}
function allowed(req,x){return x&&(isAdmin(req.user)||x.empresa_id===req.user.empresa_id)}
function norm(b={}){return {codigo:String(b.codigo||"").trim(),fecha_inicio:String(b.fecha_inicio||"").trim(),fecha_fin:String(b.fecha_fin||"").trim(),cantidad:Math.max(1,Number(b.cantidad||1)),precio:Number(b.precio||0),descuento:Number(b.descuento||0),dia_facturacion:Math.min(31,Math.max(1,Number(b.dia_facturacion||1))),renovacion_automatica:Number(b.renovacion_automatica)?1:0,estado:String(b.estado||"Activa"),observaciones:String(b.observaciones||"").trim()}}
function base(req){const q=String(req.query.q||"").trim(),estado=String(req.query.estado||""),empresa=isAdmin(req.user)&&Number(req.query.empresa_id)?Number(req.query.empresa_id):req.user.empresa_id,plan=Number(req.query.plan_id||0),cliente=Number(req.query.cliente_id||0),params=[empresa];let sql=`SELECT s.*,c.nombre cliente,c.razon_social,c.nombre_comercial,p.nombre plan,p.codigo plan_codigo,sv.nombre servicio FROM suscripciones s JOIN clientes c ON c.id=s.cliente_id JOIN planes p ON p.id=s.plan_id JOIN servicios sv ON sv.id=p.servicio_id WHERE s.empresa_id=?`;if(q){sql+=" AND (s.codigo LIKE ? OR c.nombre LIKE ? OR c.razon_social LIKE ? OR c.nombre_comercial LIKE ? OR p.nombre LIKE ? OR sv.nombre LIKE ?)";const l=`%${q}%`;params.push(l,l,l,l,l,l)}if(estado){sql+=" AND s.estado=?";params.push(estado)}if(plan){sql+=" AND s.plan_id=?";params.push(plan)}if(cliente){sql+=" AND s.cliente_id=?";params.push(cliente)}sql+=" ORDER BY s.fecha_inicio DESC,s.id DESC LIMIT 1000";return [sql,params]}
r.get("/catalogos",requireAuth,requirePermission("suscripciones.ver"),(req,res)=>{const empresa=isAdmin(req.user)&&Number(req.query.empresa_id)?Number(req.query.empresa_id):req.user.empresa_id;res.json({clientes:db.prepare("SELECT id,nombre,razon_social,nombre_comercial,empresa_id FROM clientes WHERE empresa_id=? AND estado=1 ORDER BY COALESCE(NULLIF(razon_social,''),nombre)").all(empresa),planes:db.prepare("SELECT p.id,p.empresa_id,p.nombre,p.codigo,p.precio,p.periodicidad,s.nombre servicio FROM planes p JOIN servicios s ON s.id=p.servicio_id WHERE p.empresa_id=? AND p.estado=1 ORDER BY p.nombre").all(empresa)})});
r.get("/export",requireAuth,requirePermission("suscripciones.exportar"),(req,res)=>{const [sql,params]=base(req);const exportSql=sql.replace("SELECT s.*,c.nombre cliente,c.razon_social,c.nombre_comercial,p.nombre plan,p.codigo plan_codigo,sv.nombre servicio","SELECT s.codigo,c.nombre cliente,c.razon_social,p.nombre plan,sv.nombre servicio,s.fecha_inicio,s.fecha_fin,s.cantidad,s.precio,s.descuento,s.dia_facturacion,s.renovacion_automatica,s.estado,s.observaciones").replace(" LIMIT 1000","");const rows=db.prepare(exportSql).all(...params);const h=["codigo","cliente","razon_social","plan","servicio","fecha_inicio","fecha_fin","cantidad","precio","descuento","dia_facturacion","renovacion_automatica","estado","observaciones"],cell=v=>`"${String(v??"").replaceAll('"','""')}"`;res.setHeader("Content-Type","text/csv; charset=utf-8");res.setHeader("Content-Disposition",`attachment; filename="suscripciones-itgps-${new Date().toISOString().slice(0,10)}.csv"`);res.send("\ufeff"+[h.join(","),...rows.map(x=>h.map(k=>cell(x[k])).join(","))].join("\n"))});
r.get("/",requireAuth,requirePermission("suscripciones.ver"),(req,res)=>{const [sql,params]=base(req);res.json({suscripciones:db.prepare(sql).all(...params)})});
r.get("/:id",requireAuth,requirePermission("suscripciones.ver"),(req,res)=>{const x=row(Number(req.params.id));if(!allowed(req,x))return res.status(404).json({error:"Suscripción no encontrada"});res.json({suscripcion:x})});
r.post("/",requireAuth,requirePermission("suscripciones.crear"),(req,res)=>{const d=norm(req.body),empresa=isAdmin(req.user)&&Number(req.body.empresa_id)?Number(req.body.empresa_id):req.user.empresa_id,cliente=db.prepare("SELECT id,empresa_id,estado FROM clientes WHERE id=?").get(Number(req.body.cliente_id||0)),plan=db.prepare("SELECT id,empresa_id,estado FROM planes WHERE id=?").get(Number(req.body.plan_id||0));if(!cliente||cliente.empresa_id!==empresa||!cliente.estado)return res.status(400).json({error:"El cliente seleccionado no es válido"});if(!plan||plan.empresa_id!==empresa||!plan.estado)return res.status(400).json({error:"El plan seleccionado no es válido o está inactivo"});if(!d.fecha_inicio)return res.status(400).json({error:"La fecha de inicio es obligatoria"});if(d.precio<0||d.descuento<0||d.descuento>d.precio)return res.status(400).json({error:"Valores comerciales no válidos"});try{const x=db.prepare(`INSERT INTO suscripciones(empresa_id,cliente_id,plan_id,codigo,fecha_inicio,fecha_fin,cantidad,precio,descuento,dia_facturacion,renovacion_automatica,estado,observaciones,creado_por,fecha_actualizacion) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)`).run(empresa,cliente.id,plan.id,d.codigo,d.fecha_inicio,d.fecha_fin,d.cantidad,d.precio,d.descuento,d.dia_facturacion,d.renovacion_automatica,d.estado,d.observaciones,req.user.id);audit(req,"CREAR",`Creó suscripción ${d.codigo||x.lastInsertRowid}`,empresa);res.status(201).json({ok:true,id:Number(x.lastInsertRowid)})}catch(e){if(String(e.message).includes("UNIQUE"))return res.status(409).json({error:"Ya existe una suscripción con ese código en la empresa"});res.status(500).json({error:"No fue posible crear la suscripción"})}});
r.put("/:id",requireAuth,requirePermission("suscripciones.editar"),(req,res)=>{const id=Number(req.params.id),cur=row(id);if(!allowed(req,cur))return res.status(404).json({error:"Suscripción no encontrada"});const d=norm(req.body),cliente=db.prepare("SELECT id,empresa_id,estado FROM clientes WHERE id=?").get(Number(req.body.cliente_id||cur.cliente_id)),plan=db.prepare("SELECT id,empresa_id,estado FROM planes WHERE id=?").get(Number(req.body.plan_id||cur.plan_id));if(!cliente||cliente.empresa_id!==cur.empresa_id||!cliente.estado)return res.status(400).json({error:"El cliente seleccionado no es válido"});if(!plan||plan.empresa_id!==cur.empresa_id||!plan.estado)return res.status(400).json({error:"El plan seleccionado no es válido o está inactivo"});try{db.prepare(`UPDATE suscripciones SET cliente_id=?,plan_id=?,codigo=?,fecha_inicio=?,fecha_fin=?,cantidad=?,precio=?,descuento=?,dia_facturacion=?,renovacion_automatica=?,estado=?,observaciones=?,fecha_actualizacion=CURRENT_TIMESTAMP WHERE id=?`).run(cliente.id,plan.id,d.codigo,d.fecha_inicio,d.fecha_fin,d.cantidad,d.precio,d.descuento,d.dia_facturacion,d.renovacion_automatica,d.estado,d.observaciones,id);audit(req,"EDITAR",`Editó suscripción ${id}`,cur.empresa_id);res.json({ok:true})}catch(e){res.status(409).json({error:"No fue posible actualizar la suscripción"})}});
r.delete("/:id",requireAuth,requirePermission("suscripciones.eliminar"),(req,res)=>{const id=Number(req.params.id),cur=row(id);if(!allowed(req,cur))return res.status(404).json({error:"Suscripción no encontrada"});const nuevo=cur.estado==="Activa"?"Suspendida":cur.estado==="Suspendida"?"Activa":"Activa";db.prepare("UPDATE suscripciones SET estado=?,fecha_actualizacion=CURRENT_TIMESTAMP WHERE id=?").run(nuevo,id);audit(req,nuevo==="Activa"?"ACTIVAR":"SUSPENDER",`${nuevo==="Activa"?"Activó":"Suspendió"} suscripción ${id}`,cur.empresa_id);res.json({ok:true,estado:nuevo})});
export default r;
