import "dotenv/config";import express from "express";import cors from "cors";import cookieParser from "cookie-parser";import path from "node:path";import {fileURLToPath} from "node:url";import { runMigrations } from "./db/migrate.js";import { db, initPostgresMirror, isPostgresMode } from "./db/database.js";import auth from "./routes/auth.js";import users from "./routes/users.js";import companies from "./routes/companies.js";import dashboard from "./routes/dashboard.js";import roles from "./routes/roles.js";import audit from "./routes/audit.js";import clients from "./routes/clients.js";import prospects from "./routes/prospects.js";import assets from "./routes/assets.js";import equipment from "./routes/equipment.js";import sim from "./routes/sim.js";import m2m from "./routes/m2m.js";import reports from "./routes/reports.js";import gestion from "./routes/gestion.js";import consolidacion from "./routes/consolidacion.js";import operacionGps from "./routes/operacionGps.js";import services from "./routes/services.js";import plans from "./routes/plans.js";import subscriptions from "./routes/subscriptions.js";import quotes from "./routes/quotes.js";import invoices from "./routes/invoices.js";import cartera from "./routes/cartera.js";import financiero from "./routes/financiero.js";import facturacionRecurrente from "./routes/facturacionRecurrente.js";import renewals from "./routes/renewals.js";import contracts from "./routes/contracts.js";import ordenesServicio from "./routes/ordenesServicio.js";import documents from "./routes/documents.js";import templates from "./routes/templates.js";import customReports from "./routes/customReports.js";import exportsRouter from "./routes/exports.js";import comercial from "./routes/comercial.js";import integraciones from "./routes/integraciones.js";import configuracion from "./routes/configuracion.js";import { processScheduledNotifications } from "./services/notifications.js";await initPostgresMirror();if(!isPostgresMode())runMigrations();if(process.env.NODE_ENV==="production"&&!process.env.JWT_SECRET)throw new Error("JWT_SECRET es obligatorio en producción");const app=express();app.use(cors({origin:process.env.FRONTEND_ORIGIN||"http://localhost:5173",credentials:true}));app.use(express.json({limit:"12mb"}));app.use(express.urlencoded({extended:true,limit:"12mb"}));app.use(cookieParser());
const rateBuckets=new Map();
app.use((req,res,next)=>{const key=req.ip||"unknown",now=Date.now(),bucket=rateBuckets.get(key)||{start:now,count:0};if(now-bucket.start>=60000){bucket.start=now;bucket.count=0;}bucket.count++;rateBuckets.set(key,bucket);if(bucket.count>300)return res.status(429).json({error:"Demasiadas solicitudes. Intente nuevamente en unos segundos."});res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("X-Frame-Options","DENY");res.setHeader("Referrer-Policy","same-origin");res.setHeader("Permissions-Policy","camera=(),microphone=(),geolocation=()");if(process.env.NODE_ENV==="production")res.setHeader("Strict-Transport-Security","max-age=31536000; includeSubDomains");next();});app.get("/api/health",(_,s)=>{try{db.prepare("SELECT 1 AS ok").get();return s.json({ok:true,app:"IT GPS APP",database:isPostgresMode()?"postgresql":"sqlite"});}catch(e){return s.status(503).json({ok:false,app:"IT GPS APP",error:"database_unavailable"});}});app.use("/api/auth",auth);app.use("/api/users",users);app.use("/api/companies",companies);app.use("/api/dashboard",dashboard);app.use("/api/roles",roles);app.use("/api/auditoria",audit);app.use("/api/clientes",clients);app.use("/api/prospectos",prospects);app.use("/api/activos",assets);app.use("/api/equipos",equipment);app.use("/api/sim",sim);app.use("/api/m2m",m2m);app.use("/api/reportes",reports);app.use("/api/gestion",gestion);app.use("/api/consolidacion",consolidacion);app.use("/api/operacion-gps",operacionGps);app.use("/api/servicios",services);app.use("/api/planes",plans);app.use("/api/suscripciones",subscriptions);app.use("/api/cotizaciones",quotes);app.use("/api/facturas",invoices);app.use("/api/cartera",cartera);app.use("/api/financiero",financiero);app.use("/api/facturacion-recurrente",facturacionRecurrente);app.use("/api/renovaciones",renewals);app.use("/api/contratos",contracts);app.use("/api/ordenes-servicio",ordenesServicio);app.use("/api/documentos",documents);app.use("/api/plantillas-documentos",templates);app.use("/api/reportes-personalizados",customReports);app.use("/api/exportaciones",exportsRouter);app.use("/api/comercial",comercial);app.use("/api/integraciones",integraciones);app.use("/api/configuracion",configuracion);
const frontendDist=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../../frontend/dist");
app.use(express.static(frontendDist));
app.get("/{*splat}",(req,res,next)=>{if(req.path.startsWith("/api/"))return next();res.sendFile(path.join(frontendDist,"index.html"));});app.use((err,req,res,next)=>{if(err?.type==="entity.too.large"||err?.status===413)return res.status(413).json({error:"La solicitud supera el límite permitido de 12 MB. Reduzca el tamaño de las imágenes o datos enviados."});next(err)});

export default app;

if(!process.env.VERCEL){
  app.listen(Number(process.env.PORT||3001),()=>{
    console.log("IT GPS API en http://localhost:3001");
    processScheduledNotifications().catch(e=>console.warn("[NOTIFICACIONES PROGRAMADAS]",e.message));
    setInterval(()=>processScheduledNotifications().catch(e=>console.warn("[NOTIFICACIONES PROGRAMADAS]",e.message)),60*60*1000);
  });
}
